/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import jogador.DAOJogador;
import jogador.Jogador;
import secret.Dedicatoria;

/**
 *
 * @author eluiz
 */
public class IniciarSessao extends javax.swing.JInternalFrame {

    /**
     * Creates new form IniciarSessao
     */
    public IniciarSessao() {
        initComponents();
        menuJogador = new MenuJogador();
        cadastrar = new CadastrarJogador();
        daoJogador = new DAOJogador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cadastrarBT = new javax.swing.JButton();
        iniciarBT = new javax.swing.JButton();
        nicknameTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setClosable(true);
        setTitle("Iniciar Sessão");
        setMinimumSize(new java.awt.Dimension(400, 600));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");

        cadastrarBT.setBackground(new java.awt.Color(255, 0, 187));
        cadastrarBT.setForeground(java.awt.Color.white);
        cadastrarBT.setText("CADASTRE-SE");
        cadastrarBT.setBorder(null);
        cadastrarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBTActionPerformed(evt);
            }
        });

        iniciarBT.setBackground(new java.awt.Color(140, 0, 255));
        iniciarBT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        iniciarBT.setForeground(java.awt.Color.white);
        iniciarBT.setText("INICIAR");
        iniciarBT.setBorder(null);
        iniciarBT.setBorderPainted(false);
        iniciarBT.setEnabled(false);
        iniciarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarBTActionPerformed(evt);
            }
        });

        nicknameTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                nicknameTFMouseReleased(evt);
            }
        });
        nicknameTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nicknameTFKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Digite seu nickname:");

        jLabel2.setBackground(java.awt.Color.black);
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Iniciar Sessão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(nicknameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(iniciarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarBT, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nicknameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cadastrarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cadastrarBT, iniciarBT});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarBTActionPerformed
        String nick = nicknameTF.getText().trim();        
        buscarJogador(nick);
    }//GEN-LAST:event_iniciarBTActionPerformed

    private void cadastrarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBTActionPerformed
        cadastrar();
    }//GEN-LAST:event_cadastrarBTActionPerformed

    private void nicknameTFMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nicknameTFMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nicknameTFMouseReleased

    private void nicknameTFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicknameTFKeyReleased
        // TODO add your handling code here:
        if(nicknameTF.getText().equals("")){
            iniciarBT.setEnabled(false);
        }
        else{
            iniciarBT.setEnabled(true);
        }
    }//GEN-LAST:event_nicknameTFKeyReleased

    private void cadastrar(){
        getParent().add(cadastrar);
        cadastrar.setVisible(true);
        cadastrar.toFront();
        dispose();
    }
    
    private void buscarJogador(String nick){
        boolean encontrado = false;
        
        for(Jogador j: daoJogador.listar("")){
            if(j.getNickname().equals(nick)){
                encontrado = true;
                jogador = j; 
            }
        }
        
        if(encontrado == true){
            menuJogador.apresentacaoLB.setText("Seja bem-vindo,\n"+jogador.getNickname()+"!");
            getParent().add(menuJogador);
            menuJogador.setVisible(true);
        }
        else{
            int opc = JOptionPane.showConfirmDialog(this, "Não foi possível encontrar o jogador "+nick+"!\nDeseja cadastra-lo?");
            if(opc == 0){
                cadastrar();
            }
        }
    }

    public static Jogador getJogador() {
        return jogador;
    }

    public static void setJogador(Jogador jogador) {
        IniciarSessao.jogador = jogador;
    }
    
    public static Jogador jogador;
    private MenuPrincipal menuPrincipal;
    private MenuJogador menuJogador;
    private CadastrarJogador cadastrar;
    private DAOJogador daoJogador;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarBT;
    private javax.swing.JButton iniciarBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nicknameTF;
    // End of variables declaration//GEN-END:variables
}
