/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author eluiz
 */
public class MenuJogador extends javax.swing.JInternalFrame {

    /**
     * Creates new form MenuJogador
     */
    public MenuJogador() {
        initComponents();
        modoJogo = new ModoJogo();
        ranking = new Ranking();
        config = new Configuracoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jogarBT = new javax.swing.JButton();
        rankingBT = new javax.swing.JButton();
        configuracoes = new javax.swing.JButton();
        sairBT = new javax.swing.JButton();
        apresentacaoLB = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setMaximizable(true);
        setTitle("Menu Principal");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jogarBT.setBackground(new java.awt.Color(255, 93, 28));
        jogarBT.setForeground(java.awt.Color.white);
        jogarBT.setText("JOGAR");
        jogarBT.setBorder(null);
        jogarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarBTActionPerformed(evt);
            }
        });

        rankingBT.setBackground(new java.awt.Color(0, 63, 255));
        rankingBT.setForeground(java.awt.Color.white);
        rankingBT.setText("RANKING");
        rankingBT.setBorder(null);
        rankingBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankingBTActionPerformed(evt);
            }
        });

        configuracoes.setBackground(new java.awt.Color(140, 0, 255));
        configuracoes.setForeground(new java.awt.Color(255, 255, 255));
        configuracoes.setText("CONFIGURAÇÕES");
        configuracoes.setBorder(null);
        configuracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracoesActionPerformed(evt);
            }
        });

        sairBT.setBackground(new java.awt.Color(255, 0, 187));
        sairBT.setForeground(java.awt.Color.white);
        sairBT.setText("SAIR");
        sairBT.setBorder(null);
        sairBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jogarBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rankingBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(configuracoes, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(sairBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jogarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(rankingBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configuracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sairBT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        apresentacaoLB.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        apresentacaoLB.setForeground(java.awt.Color.white);
        apresentacaoLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apresentacaoLB.setText("Seja bem-vindo, Jogador!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apresentacaoLB)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(apresentacaoLB)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarBTActionPerformed
        // TODO add your handling code here:
        getParent().add(modoJogo);
        modoJogo.setVisible(true);
    }//GEN-LAST:event_jogarBTActionPerformed

    private void rankingBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankingBTActionPerformed
        // TODO add your handling code here:
        getParent().add(ranking);
        ranking.setVisible(true);
    }//GEN-LAST:event_rankingBTActionPerformed

    private void configuracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracoesActionPerformed
        // TODO add your handling code here:
        getParent().add(config);
        config.setVisible(true);
    }//GEN-LAST:event_configuracoesActionPerformed

    private void sairBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBTActionPerformed
        // TODO add your handling code here:
        int opc = JOptionPane.showConfirmDialog(this, "Deseja encerrar a sessão?", "Encerrar Sessão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(opc == 0){
            dispose();
        }
    }//GEN-LAST:event_sairBTActionPerformed
    
    private ModoJogo modoJogo;
    private Ranking ranking;
    private Configuracoes config;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel apresentacaoLB;
    private javax.swing.JButton configuracoes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jogarBT;
    private javax.swing.JButton rankingBT;
    private javax.swing.JButton sairBT;
    // End of variables declaration//GEN-END:variables
}
